import type { Venue } from '@prisma/client';
import cuid from 'cuid';
export const dummmyVenues: Venue[] = [
    {
        venueId: cuid(),
        name: "Aston Denpasar Hotel & Convention Center",
        address: "Jl. Gatot Subroto Barat No.283, Dauh Puri Klod, Kec. Denpasar Barat, Kota Denpasar, Bali 80117",
        state: "Bali",
        country: "Indonesia",
        phone: "0361 411999",
        email: "astonhotel@gmail.com",
        website: "https://www.astonhotels.com",
        description: "Aston Denpasar Hotel & Convention Center is a 4-star hotel located in the heart of Denpasar, Bali. The hotel offers 215 rooms and suites, 12 meeting rooms, a ballroom, a restaurant, a bar, a swimming pool, a gym, and a spa.",
        capacity: 400,
        rating: 4.0,
        latitude: -8.670458,
        longitude: 115.206686,
        amenities: ["Tables", "Chairs", "Stage", "Projector", "Sound System", "Lighting", "Catering", "Parking", "Security"],
        image: "/img/venues/Venue4.png",
        price: BigInt(458000),
        createdAt: new Date(),
        updatedAt: new Date(),
        zip: "80117"
    },
    {
        venueId: cuid(),
        name: "hang n Out Cafe",
        address: "Jakarta Barat",
        state: "Jakarta",
        country: "Indonesia",
        phone: "085232674919",
        email: "hangout@gmail.com",
        website: "https://www.example.com",
        description: "Good cafe to hang out",
        capacity: 50,
        rating: 4.8,
        latitude: 37.7749,
        longitude: -122.4194,
        amenities: ["Tables", "Chairs", "Stage"],
        image: "/img/venues/Venue8.png",
        price: BigInt(300000),
        createdAt: new Date(),
        updatedAt: new Date(),
        zip: "56832"
    },
    {
        venueId: cuid(),
        name: "The Ritz-Carlton Jakarta, Pacific Place",
        address: "Sudirman Central Business District (SCBD), Jl. Jendral Sudirman Kav. 52-53, Senayan, Kebayoran Baru, Jakarta Selatan, DKI Jakarta 12190",
        state: "Jakarta",
        country: "Indonesia",
        phone: "021 25501888",
        email: "ritzcarlton@gmail.com",
        website: "https://www.ritzcarlton.com",
        description: "The Ritz-Carlton Jakarta, Pacific Place is a 5-star hotel located in the heart of Jakarta, Indonesia. The hotel offers 62 rooms and suites, 5 meeting rooms, a ballroom, a restaurant, a bar, a swimming pool, a gym, and a spa.",
        capacity: 200,
        rating: 4.5,
        latitude: -6.2244,
        longitude: 106.8097,
        amenities: ["Tables", "Chairs", "Stage", "Projector", "Sound System", "Lighting", "Catering", "Parking", "Security"],
        image: "/img/venues/Venue2.png",
        price: BigInt(1000000),
        createdAt: new Date(),
        updatedAt: new Date(),
        zip: "12190"
    },
    {
        venueId: cuid(),
        name: "The Westin Resort Nusa Dua, Bali",
        address: "Kawasan Pariwisata Nusa Dua, BTDC Lot N-3, Nusa Dua, Bali 80363",
        state: "Bali",
        country: "Indonesia",
        phone: "0361 771906",
        email: "",
        website: "https://www.marriott.com",
        description: "The Westin Resort Nusa Dua, Bali is a 5-star hotel located in the heart of Nusa Dua, Bali. The hotel offers 433 rooms and suites, 16 meeting rooms, a ballroom, 5 restaurants, 3 bars, 3 swimming pools, a gym, and a spa.",
        capacity: 500,
        rating: 4.3,
        latitude: -8.8006,
        longitude: 115.2286,
        amenities: ["Tables", "Chairs", "Stage", "Projector", "Sound System", "Lighting", "Catering", "Parking", "Security"],
        image: "/img/venues/Venue16.png",
        price: BigInt(1500000),
        createdAt: new Date(),
        updatedAt: new Date(),
        zip: "80363"
    }
];